baseURL = 'https://samuraismokey.com/'
languageCode = 'en-us'
title = 'Samurai Smokey'
theme = 'ananke'

[[menu.main]]
  name = "Chapters"
  url = "/categories/chapter-1/"
  weight = 10

[[menu.main]]
  name = "Gallery"
  url = "/gallery/"
  weight = 20

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 30

[params]
  custom_css = ["css/custom.css"]